# Generated by Django 4.1.2 on 2023-06-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketbookapi', '0002_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_status',
            name='reciept_num',
        ),
    ]
