# Generated by Django 4.1.2 on 2023-06-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketbookapi', '0003_remove_payment_status_reciept_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_status',
            name='payment_complete',
        ),
    ]
