# Generated by Django 4.1.2 on 2023-06-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketbookapi', '0004_remove_payment_status_payment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_status',
            name='customer_details',
        ),
        migrations.AddField(
            model_name='payment_status',
            name='movie_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
