# Generated by Django 4.1.2 on 2023-06-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketbookapi', '0006_remove_payment_status_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_status',
            name='payment_complete',
            field=models.IntegerField(default=0),
        ),
    ]
