# Generated by Django 4.1.2 on 2023-06-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketbookapi', '0007_payment_status_payment_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_status',
            old_name='payment_complete',
            new_name='movie_id',
        ),
    ]
