# Generated by Django 4.1.2 on 2023-06-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketbookapi', '0008_rename_payment_complete_payment_status_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_status',
            name='movie_id',
        ),
    ]
