# Generated by Django 4.1.2 on 2023-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_show_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='duration',
            field=models.DateField(max_length=40, null=True),
        ),
    ]
