# Generated by Django 4.1.2 on 2023-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_show_site', '0003_alter_movie_details_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='is_active',
            field=models.SmallIntegerField(default=1),
        ),
    ]
