# Generated by Django 4.1.2 on 2023-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_show_site', '0005_alter_movie_details_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_details',
            name='language',
        ),
        migrations.AddField(
            model_name='movie_details',
            name='language',
            field=models.ManyToManyField(to='admin_show_site.movie_language'),
        ),
    ]
