# Generated by Django 4.1.2 on 2023-06-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_show_site', '0006_remove_movie_details_language_movie_details_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='trailer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
